import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import * as dotenv from 'dotenv';
import * as path from 'path';
import * as fs from 'fs';

// Load environment variables
dotenv.config({ path: path.join(process.cwd(), '.env.local') });

async function uploadCincinnatiDocs() {
  console.log('📤 Uploading Cincinnati Documents to S3...\n');

  const s3Client = new S3Client({
    region: process.env.AWS_REGION || 'us-east-2',
    credentials: {
      accessKeyId: process.env.AWS_S3_ACCESS_KEY_ID || '',
      secretAccessKey: process.env.AWS_S3_SECRET_ACCESS_KEY || '',
    },
  });

  const bucketName = process.env.AWS_S3_BUCKET || 'civix-documents';

  try {
    // Upload the full ordinances text file
    const ordinancesPath = path.join(process.cwd(), 'public', 'ordinances', 'cincinnati', 'full-ordinances.txt');

    if (!fs.existsSync(ordinancesPath)) {
      console.error(`❌ File not found: ${ordinancesPath}`);
      return;
    }

    const fileContent = fs.readFileSync(ordinancesPath);
    const fileStats = fs.statSync(ordinancesPath);
    const fileSizeMB = (fileStats.size / 1024 / 1024).toFixed(2);

    console.log(`📄 Uploading: full-ordinances.txt (${fileSizeMB} MB)`);

    await s3Client.send(new PutObjectCommand({
      Bucket: bucketName,
      Key: 'cincinnati-oh/ordinances/full-ordinances.txt',
      Body: fileContent,
      ContentType: 'text/plain',
      Metadata: {
        'jurisdiction': 'cincinnati-oh',
        'document-type': 'municipal-code',
        'uploaded-date': new Date().toISOString(),
      },
    }));

    console.log('✓ Successfully uploaded to: cincinnati-oh/ordinances/full-ordinances.txt\n');

    // Create a README in the ordinances folder
    const readmeContent = `# Cincinnati Ordinances

**Last Updated**: ${new Date().toISOString().split('T')[0]}

## Files in this folder:

- **full-ordinances.txt** - Complete Cincinnati Municipal Code text file
  - Size: ${fileSizeMB} MB
  - Used to generate 1,418 searchable chunks in RDS
  - Chunked and embedded for semantic search

## What's Next:

### Missing Data for Complete Cincinnati Coverage:

1. **Zoning Data**
   - Parcel-to-zone mapping (CSV/shapefile)
   - Zoning map PDF
   - Zoning code definitions

2. **Building Codes**
   - International Building Code (IBC) 2021
   - International Residential Code (IRC) 2021
   - Cincinnati local amendments

3. **Permit Requirements**
   - Permit application forms (PDFs)
   - Fee schedules
   - Processing time guidelines
   - Required documents checklist

## Data Sources:

- **Ordinances**: Already loaded ✅
- **Zoning**: https://data.cincinnati-oh.gov
- **Building Dept**: https://www.cincinnati-oh.gov/buildings/
- **Planning**: https://www.cincinnati-oh.gov/planning/zoning/

---

Generated by Civix data loading system
`;

    await s3Client.send(new PutObjectCommand({
      Bucket: bucketName,
      Key: 'cincinnati-oh/ordinances/README.md',
      Body: readmeContent,
      ContentType: 'text/markdown',
    }));

    console.log('✓ Created README.md in ordinances folder\n');

    console.log('✅ Upload complete!\n');
    console.log('📊 S3 Bucket Status:');
    console.log('   ✓ Cincinnati ordinances organized');
    console.log('   ✓ Folder structure ready for additional data');
    console.log('\n📁 Next steps:');
    console.log('   1. Obtain Cincinnati zoning data');
    console.log('   2. Download building code PDFs');
    console.log('   3. Get permit requirement documents');
    console.log('   4. Upload to respective S3 folders');

  } catch (error: any) {
    console.error('\n❌ ERROR:', error.message);
  }
}

uploadCincinnatiDocs();
